/// Flutter icons Storage
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Storage
///      fonts:
///       - asset: fonts/Storage.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
///
import 'package:flutter/widgets.dart';

class StorageIcons {
  StorageIcons._();

  static const _kFontFam = 'Storage';
  static const String? _kFontPkg = null;

  static const IconData craft = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData chest = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robot = IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
